### ISSUE TITLE
Lists feature: small UI bugs

### ISSUE THREAD

**Issue by mushon** [OpenBudget/budgetkey-app#2]
- [ ] icon should be filled as soon as it is clicked
- [ ] all the card should be clickable (not only the title)
- [ ] show pointer on hover (everywhere)
- [ ] show remove from list icon when hovering on current list (<img width="99" alt="image" src="https://github.com/OpenBudget/budgetkey-app/assets/27123/c9b6bd47-3dcf-4403-9b93-9b8acbf9777e">)
- [ ] Add hover state to editable text
- [ ] Update trash icon (should be larger)
- [ ] Clicking the title of a list in the popup should open it in the sidebar
- [ ] Clicking רשימה חדשה currently requires an extra click to edit. Make it take focus on the first click.
- [ ] Missing the dropdown option in the list popup
- [ ] Add tooltip to button ([figma](https://www.figma.com/file/MwcrkK9dPtuXFVNGQczgPj/obudget?type=design&node-id=332-13221&mode=design&t=6hKSz4BzsmaoH04T-4))

**Comment by akariv** [comment]
> show pointer on hover (everywhere)
I couldn't find where it doesn't show...

**Comment by akariv** [comment]
@mushon a few questions above (make sure to open the issue cause I updated the comment).

I will fix all the rest.

**Comment by akariv** [comment]
> all editable areas do not show pointer

They show a 'text' cursor, as it's commonly expected on text editable areas

> username/image should take to all the lists by the user

There's no such view at the moment, I agree that when the view exists it should link there.

> yes

OK

> You are right. Forget about it…

OK

> opens the page on every click on the card

Which page and which card? Can you show me what you mean in Zoom?

**Comment by akariv** [comment]
> Which page and which card? Can you show me what you mean in Zoom?

nvm, I saw what you mean - it got in while fixing other things. Should be ok now.
